### ISSUE TITLE
Deploy backend azure

### ISSUE THREAD

**Issue by alcides07** [tads-cnat/ifsolve#157]
**Tempo previsto (em horas):** 12

**Tempo gasto (em horas):**

**Complexidade (baixa | média | alta):** alta

**Qualidade (baixa | média | alta):**

**Descrição**

**Comment by diogoodiego** [comment]
@alcides07 @matRaph Esse foi o Dockerfile utilizado para gerar a imagem diogoodiego/ifsolve
```yml
# Base image
FROM python:3.10

# Set the working directory
WORKDIR /code

# Copy the requirements file
COPY requirements.txt .

# Copy the project code
COPY . .


# Install dependencies
RUN pip install -r requirements.txt
```

E esse é o docker-compose.
```yml
version: "3.9"

services:
  postgresql:
    image: postgres
    volumes:
      - postgres_data:/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ifsolve
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    working_dir: /code/config/
    image: diogoodiego/ifsolve
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - default
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      postgresql:
        condition: service_healthy
volumes:
  postgres_data:
```
