### ISSUE TITLE
Utilizar healthcheck no docker-compose do back-end

### ISSUE THREAD

**Issue by diogoodiego** [tads-cnat/ifsolve#180]
**Tempo previsto (em horas):** 1

**Tempo gasto (em horas):**

**Complexidade (baixa | média | alta):** média

**Qualidade (baixa | média | alta):**

**Descrição**
Estamos com um problema que ocorre quando o container do django tenta se conectar com o postegres, mas caso tenha algum erro com a conexão django+postegres o container do backend para de executar.

Uma possivel correção é adotar o uso do healthcheck para verificar o estado do container postegres seguindo o exemplo abaixo:
```yml
version: "3.9"

services:
  postgresql:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ifsolve
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    working_dir: /code/config
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - default
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/code
    depends_on:
      postgresql:
        condition: service_healthy

```
